server:
  port: 8066
spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/spring-boot-h2
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  secondary-datasource:
    url: localhost:8091
    username: Administrator
    password: password

